---
title: "condition_plotting"
author: "Gustav Idun Sloth"
date: "2023-12-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(babynames)
library(hrbrthemes)
library(scales)
library(betareg)
library(boot)
library(VGAM)
library(nnet)
library(ggpubr)
```

## loading data

```{r data}
baseline <- read_csv("data/conditions/baseline.csv")
cond1 <- read_csv("data/conditions/cond1.csv")
cond2 <- read_csv("data/conditions/cond2.csv")
cond3 <- read_csv("data/conditions/cond3.csv")
all_conds <- read_csv("data/conditions/refactored_large_final.csv")

```
## Plotting Distributions

```{r dists}

baseline <- all_conds %>% filter(condition == "baseline") %>% 
  ggplot(aes(x = probability, group = category, fill = category)) +
    geom_density(adjust=1.5) +
    theme_minimal() +
    facet_wrap(~category) +
    theme(
      legend.position="none",
      panel.spacing = unit(1, "lines"),
      axis.ticks.x=element_blank()
    )+
  ylim(0,2)

cond1 <- all_conds %>% filter(condition == "cond1") %>% 
  ggplot(aes(x = probability, group = category, fill = category)) +
    geom_density(adjust=1.5) +
    theme_minimal() +
    facet_wrap(~category) +
    theme(
      legend.position="none",
      panel.spacing = unit(1, "lines"),
      axis.ticks.x=element_blank()
    ) +
  ylim(0,2)

cond2 <- all_conds %>% filter(condition == "cond2") %>% 
  ggplot(aes(x = probability, group = category, fill = category)) +
    geom_density(adjust=1.5) +
    theme_minimal() +
    facet_wrap(~category) +
    theme(
      legend.position="none",
      panel.spacing = unit(1, "lines"),
      axis.ticks.x=element_blank()
    ) +
  ylim(0,2)

cond3 <- all_conds %>% filter(condition == "cond3") %>% 
  ggplot(aes(x = probability, group = category, fill = category)) +
    geom_density(adjust=1.5) +
    theme_minimal() +
    facet_wrap(~category) +
    theme(
      legend.position="none",
      panel.spacing = unit(1, "lines"),
      axis.ticks.x=element_blank()
    ) +
  ylim(0,2)

ggarrange(baseline, cond1, cond2, cond3, labels = c("Baseline", "Cond 1", "Cond 2", "Cond 3"), ncol = 2, nrow = 2)

```
## Plotting Means

```{r mean plotting}

mean_group <- all_conds %>% group_by(condition, category) %>% summarise(mean = mean(probability)) %>% as.data.frame()

mean_plot <- ggplot(filter(mean_group, category != "medium"), aes(group=category, y = mean, x = condition, fill = category)) +
  geom_bar(stat="identity", position=position_dodge()) +
  coord_cartesian(ylim = c(0.2, 0.4)) +
  theme_minimal()

mean_plot

ggsave("plots/mean_plot.png", plot = mean_plot, width = 4, height = 3)

```



## Beta Regression

```{r beta regression}

model_beta <- function(data){

  categories_cond <- list(
    "low" = filter(data, category == "low"),
    "medium" = filter(data, category == "medium"),
    "high" = filter(data, category == "high")
  )
  
  models <- list(
    "low" = betareg(probability ~ condition, data = categories_cond$low),
    "medium" = betareg(probability ~ condition, data = categories_cond$medium),
    "high" = betareg(probability ~ condition, data = categories_cond$high)
  )
  
  return(models)
  
}

summary(model_beta(all_conds)$low)

boot::inv.logit(-0.8897 + 0.4403)

#summary(betareg(probability ~ condition + condition:category, data = all_conds))

```
## Testing Dataset

```{r testing data}

test_df <- read_csv("data/testing_final_predicts.csv")

test_cor <- filter(test_df, correct == "TRUE")

nrow(test_cor)/nrow(test_df)

```